### ISSUE TITLE
faild to compile with gcc 5.4.0

### ISSUE THREAD

**Issue by rosenk** [jameswalmsley/kconfig-frontends#4]
```
In file included from yconf.c:2459:0:
menu.c: In function ‘get_symbol_str’:
menu.c:567:18: error: ‘jump’ may be used uninitialized in this function [-Werror=maybe-uninitialized]
     jump->offset = r->len - 1;
                  ^
menu.c:528:19: note: ‘jump’ was declared here
  struct jump_key *jump;
                   ^
cc1: all warnings being treated as errors
```
